---
driver:
  name: vagrant

provisioner:
  name: policyfile_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: "../../data_bags"
    encrypted_data_bag_secret_key_path: "../../.chef/secret.pem"
    attributes:
